### ISSUE TITLE
Parse JSON with variable key values

### ISSUE THREAD

**Issue by patricks** [tristanhimmelman/AlamofireObjectMapper#172]
I have a JSON structure which is structures like this:

```
{  
   "400161":{  
      "name":"Foo",
      "internet":""
   },
   "400101":{  
      "name":"Bar",
      "internet":""
   }
}
```

Is there any way to parse this JSON, where the key is always different? The `Mappable` object should also include the the "id".

**Comment by liltimtim** [comment]
You could create a mappable object with properties name and internet and feed the "value" of the key into the init with "map" function. 

For example:

let data = responseData.toJSON() 

for (key, value) in data {
   let map = Map(data[key])
   let innerObject = InnerObject(map)
}

this is sudo code by the way.  But since your inner object of the variable keys are in fact JSON objects you should be able to map those "400161" key's value to an object and then do whatever you want with it.
