### ISSUE TITLE
Support for ImmutableMappable

### ISSUE THREAD

**Issue by txaiwieser** [tristanhimmelman/AlamofireObjectMapper#181]
Is anyone looking into this? I know its still on beta on ObjectMapper, but it should work.

Probably needs some tests, I'm going to try write some later

**Comment by txaiwieser** [comment]
I did some work on this issue, ObjectMapper fixed the error already, I added a test to cover.
here: #182

**Comment by Asich** [comment]
I tried to work with ObjectMapper with classes instead of struct, but then I had runtime error in ObjectMapper's Mapper.swift class in line 89.  

`assertion failed: 'ImmutableMappable' type requires throwing version of function map(JSON:)  - use 'try' before map(JSON:): file /Users/Askar/Developer/CrystalSpring/baf_swift/baf/Pods/ObjectMapper/Sources/Mapper.swift, line 110`

I used 'try' everywhere before map.

**Comment by danilobuerger** [comment]
+1

**Comment by txaiwieser** [comment]
Did you guys tried using my branch? It solves the problem

**Comment by louisdh** [comment]
Implemented in #194

**Comment by tristanhimmelman** [comment]
This has been released today in `4.1.0`.
