### ISSUE TITLE
 Generic type 'DataResponse' specialized with too few type parameters (got 1, but expected 2)

### ISSUE THREAD

**Issue by deezaster** [tristanhimmelman/AlamofireObjectMapper#285]
Versions i use:

AlamofireObjectMapper **6.1.0**
ObjectMapper **3.5.1**
Alamofire **5.0.0-rc.2**

Problem with .responseArray:

```swift
      AF.request(getUrlAPI(.GetAllMembers, apiVersion: "v4"), parameters: self.apiParams)
         
         .responseArray{ (response: DataResponse<[MemberJSON]>) in    
```

Error: 

![image](https://user-images.githubusercontent.com/1539838/64725243-7d308d80-d4d4-11e9-9c8f-edbf897c7358.png)

**Comment by aehlke** [comment]
Did you resolve this?

**Comment by recre4te** [comment]
i have this problem too.

**Comment by ozgur** [comment]
This has been fixed in https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/288

**Comment by freakdragon** [comment]
I just changed the type `DataResponse` to `AFDataResponse`.

What I had:
`responseData(completionHandler: { (dataResponse: DataResponse<Data>) in }` 

What I have now:
`responseData(completionHandler: { (dataResponse: AFDataResponse<Data>) in }`

**Comment by tristanhimmelman** [comment]
Closing as the PR to fix this has been merged and released

**Comment by suryakantkachhi** [comment]
Hi

I'm still getting this error with below pods, i tried all mentioned Git master but nothing working.

Getting this error in XCODE11 with swift 5.

When i use AFDataRequest instead of DataRequest then issue go away. i don't whether its the correct approach to resolve the same ?

Please Help me to get out of it. thanks

pod 'Alamofire', '~> 5.0.0-rc.2'
pod 'ObjectMapper', '~> 3.4'
#pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'master'
#pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'master'
#pod 'AlamofireObjectMapper', :git => 'https://github.com/ozgur/AlamofireObjectMapper.git', :branch => 'master'
pod 'AlamofireObjectMapper', '~> 6.2.0'
#pod 'AlamofireObjectMapper', '~> 5.2'
#pod 'Alamofire', '~> 4.0.0'
![Screenshot 2019-11-03 at 7 16 23 PM](https://user-images.githubusercontent.com/13748232/68086163-d5e62c00-fe6e-11e9-8e5f-8f9fc20365f6.png)

**Comment by freakdragon** [comment]
@suryakantkachhi , did you try to change `(response: DataResponse<LoginDSModel>)` to `(response: AFDataResponse<LoginDSModel>)`?

**Comment by dangquockhanh** [comment]
_ = AF.request(URL, method: .get).responseObject { (response: AFDataResponse<WeatherResponse>) in
            
            let mappedObject = response.value
                print(mappedObject?.location)

**Comment by dangquockhanh** [comment]
[AlamofireObjectMapper-6.2.0.zip](https://github.com/tristanhimmelman/AlamofireObjectMapper/files/3836692/AlamofireObjectMapper-6.2.0.zip)
see here

**Comment by DimitrisBovasianos** [comment]
DataResponse<Any,AFError>

**Comment by haroldogtf** [comment]
I am getting the same. What should I do?

**Comment by DimitrisBovasianos** [comment]
This is how i made it to work.

Response is a struct to parse the response.

```
struct Response: Codable {
    let test : String
   
}
static func getApiRequest(url:String, parameters:Dictionary<String, Any>,completion:@escaping (AFResult<Response>)->Void) {
        let headers = configureCurrentSession()
        AF.request(url,method: .get, encoding : JSONEncoding.default,headers:headers).responseDecodable { (response: AFDataResponse<Response>) in
            completion(response.result)
            return
            
        }
            
    }

```

**Comment by DonPex** [comment]
Please @tristanhimmelman, update the **README.md** inserting the latest versions for Carthage and Cocoa. I spent hours trying to solve the incompatibility issue of `AFDataResponse<T>` as parameter of `responseObject {...}`.

**Comment by partho-maple** [comment]
I tried all of the mentioned approaches but nothing worked for me.
